# Generated by Django 6.1 on 2026-10-08 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('ACCESS_DENIED', 'Access denied'), ('SENSITIVE_REVEAL', 'Sensitive data revealed'), ('REAUTH_FAILED', 'Reauthentication failed'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SEARCH', 'Search'), ('VIEW', 'View'), ('DUPLICATE_FLAG', 'Potential duplicate flagged'), ('BACKUP', 'Database backup')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_action_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='audit_ip_recent_idx'),
        ),
    ]
