# Generated by Django 6.1 on 2026-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_security_relationships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistoryentry',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, help_text='Use administrative wording only. Do not enter diagnoses or sensitive clinical details here.', max_length=255),
        ),
    ]
