# Generated by Django 6.1 on 2026-10-08 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_security_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sa_id_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'South African ID numbers must be exactly 13 digits.')], verbose_name='South African ID number'),
        ),
    ]
